# Generated by Django 2.0.7 on 2018-08-26 16:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('branch', '0003_branch_branchpin'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orderfood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderfooddate', models.DateField(default=datetime.date.today)),
                ('orderfoodquantity', models.CharField(default='', max_length=20)),
                ('orderfoodprice', models.CharField(default='', max_length=20)),
                ('orderfoodtotalamount', models.CharField(default='', max_length=20)),
                ('orderfoodbillno', models.CharField(default='', max_length=20)),
                ('orderfoodstatus', models.CharField(default='', max_length=20)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch.Branch')),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Menu')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
