# Generated by Django 2.1.1 on 2018-11-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderfood', '0002_auto_20180827_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderfood',
            old_name='orderfoodprice',
            new_name='orderitemname',
        ),
        migrations.RemoveField(
            model_name='orderfood',
            name='branch_id',
        ),
        migrations.AlterField(
            model_name='orderfood',
            name='menu_id',
            field=models.BigIntegerField(),
        ),
    ]
