# Generated by Django 2.1.1 on 2018-11-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderfood', '0005_auto_20181107_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfood',
            name='orderfoodquantity',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='orderfood',
            name='orderfoodtotalamount',
            field=models.BigIntegerField(),
        ),
    ]
