# Generated by Django 2.1.1 on 2018-11-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderfood', '0006_auto_20181110_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfood',
            name='orderfoodstatus',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
