# Generated by Django 2.1.1 on 2018-11-18 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderfood', '0008_auto_20181117_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfood',
            name='orderfoodbillno',
            field=models.CharField(default='', max_length=20),
        ),
    ]
