# Generated by Django 2.1.1 on 2018-10-22 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20180827_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedbackdate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
