# Generated by Django 2.0.7 on 2018-08-04 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stafftype', '0001_initial'),
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeename', models.CharField(default='', max_length=20)),
                ('employeeplace', models.CharField(default='', max_length=20)),
                ('employeecity', models.CharField(default='', max_length=20)),
                ('employeedistrict', models.CharField(default='', max_length=20)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch.Branch')),
                ('stafftype_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stafftype.Stafftype')),
            ],
        ),
    ]
