# Generated by Django 2.0.7 on 2018-08-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employeeage',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='employeecontact',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='employeeemail',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='employeepassword',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='employeepin',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='employeestate',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='employeeusername',
            field=models.CharField(default='', max_length=20),
        ),
    ]
