# Generated by Django 2.0.7 on 2018-08-04 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20180804_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employeedob',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='employee',
            name='employeedoj',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
