# Generated by Django 2.0.7 on 2018-08-31 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20180804_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='branch_id',
        ),
        migrations.AddField(
            model_name='employee',
            name='branchmanager_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='employeehouse',
            field=models.CharField(default='', max_length=50),
        ),
    ]
