# Generated by Django 2.1.1 on 2018-10-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20180831_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employeeemail',
            field=models.CharField(default='', max_length=50),
        ),
    ]
