# Generated by Django 2.1.1 on 2018-11-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasedetails', '0002_purchasedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedetails',
            name='itemunittotal',
            field=models.BigIntegerField(),
        ),
    ]
