# Generated by Django 2.0.7 on 2018-08-28 14:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchasehead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchaseinvoice', models.CharField(default='', max_length=20)),
                ('purchasedate', models.DateField(default=datetime.date.today)),
                ('purchasegrandtotal', models.CharField(default='', max_length=20)),
                ('agency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.Agency')),
            ],
        ),
    ]
