# Generated by Django 2.1.1 on 2018-10-20 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasehead', '0002_auto_20181007_1255'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchasedetails',
        ),
    ]
