# Generated by Django 2.1.1 on 2018-11-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billno', models.BigIntegerField()),
                ('total', models.BigIntegerField()),
                ('address', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
