# Generated by Django 2.1.1 on 2018-11-09 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20181107_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='orderfoodbillno',
            new_name='billno',
        ),
    ]
