# Generated by Django 2.1.1 on 2018-11-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0006_auto_20181110_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
