# Generated by Django 2.1.1 on 2018-11-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0007_address_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='billno',
            field=models.CharField(default='', max_length=20),
        ),
    ]
