# Generated by Django 2.1.1 on 2018-11-19 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dreport', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dreport',
            old_name='branch_id',
            new_name='branchmanager_id',
        ),
    ]
