# Generated by Django 2.0.7 on 2018-08-28 14:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orderfood', '0002_auto_20180827_1130'),
        ('branch', '0003_branch_branchpin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dailyreport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportdate', models.DateField(default=datetime.date.today)),
                ('reporttotalamount', models.CharField(default='', max_length=20)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch.Branch')),
                ('orderfood_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderfood.Orderfood')),
            ],
        ),
    ]
