# Generated by Django 2.1.1 on 2018-11-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyreport',
            name='reporttotalamount',
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='tablebook_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='branch_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='orderfood_id',
            field=models.BigIntegerField(),
        ),
    ]
