# Generated by Django 2.1.1 on 2018-11-11 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0002_auto_20181111_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyreport',
            name='branch_id',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='orderfood_id',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='tablebook_id',
        ),
    ]
