# Generated by Django 2.0.7 on 2018-08-21 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=20)),
                ('userhouse', models.CharField(default='', max_length=20)),
                ('userplace', models.CharField(default='', max_length=20)),
                ('usercity', models.CharField(default='', max_length=20)),
                ('userdistrict', models.CharField(default='', max_length=20)),
                ('userstate', models.CharField(default='', max_length=20)),
                ('userpin', models.BigIntegerField(default='')),
                ('usercontact', models.BigIntegerField(default='')),
                ('useremail', models.CharField(default='', max_length=20)),
                ('userusername', models.CharField(default='', max_length=20)),
                ('userpassword', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
