# Generated by Django 2.1.1 on 2018-10-27 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20181027_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='menupic',
        ),
    ]
