# Generated by Django 2.1.1 on 2018-10-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_menu_menupic'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menupic',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
