# Generated by Django 2.1.1 on 2018-11-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_menu_menupic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menuname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
