# Generated by Django 2.0.7 on 2018-08-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencyname', models.CharField(default='', max_length=20)),
                ('agencyplace', models.CharField(default='', max_length=20)),
                ('agencycity', models.CharField(default='', max_length=20)),
                ('agencydistrict', models.CharField(default='', max_length=20)),
                ('agencypin', models.CharField(default='', max_length=20)),
                ('agencycontact', models.CharField(default='', max_length=20)),
                ('agencyemail', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
