# Generated by Django 2.1.1 on 2018-10-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='branchmanager_id',
            field=models.BigIntegerField(default=''),
        ),
    ]
