# Generated by Django 2.0.7 on 2018-08-31 14:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('branch', '0003_branch_branchpin'),
        ('user', '0001_initial'),
        ('tabledetails', '0002_remove_table_branch_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tablebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuquantity', models.CharField(default='', max_length=20)),
                ('bookingdate', models.DateField(default=datetime.date.today)),
                ('bookingtotaltable', models.CharField(default='', max_length=20)),
                ('bookingavailable', models.CharField(default='', max_length=20)),
                ('bookingrate', models.CharField(default='', max_length=20)),
                ('bookinggrandtotal', models.CharField(default='', max_length=20)),
                ('bookingbillno', models.CharField(default='', max_length=20)),
                ('bookingstatus', models.CharField(default='', max_length=20)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch.Branch')),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Menu')),
                ('table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabledetails.Table')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
