# Generated by Django 2.1.1 on 2018-10-26 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablebook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablebook',
            name='bookingavailable',
        ),
        migrations.RemoveField(
            model_name='tablebook',
            name='bookingbillno',
        ),
        migrations.RemoveField(
            model_name='tablebook',
            name='bookinggrandtotal',
        ),
        migrations.RemoveField(
            model_name='tablebook',
            name='bookingtotaltable',
        ),
        migrations.RemoveField(
            model_name='tablebook',
            name='menu_id',
        ),
        migrations.RemoveField(
            model_name='tablebook',
            name='menuquantity',
        ),
    ]
