# Generated by Django 2.1.1 on 2018-10-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablebook', '0002_auto_20181026_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablebook',
            name='bookingtime',
            field=models.CharField(default='', max_length=20),
        ),
    ]
