# Generated by Django 2.1.1 on 2018-10-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablebook', '0003_tablebook_bookingtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablebook',
            name='user_id',
            field=models.BigIntegerField(),
        ),
    ]
