# Generated by Django 2.1.1 on 2018-10-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablebook', '0004_auto_20181026_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablebook',
            name='branch_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='tablebook',
            name='table_id',
            field=models.BigIntegerField(),
        ),
    ]
