# Generated by Django 2.1.1 on 2018-11-15 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablebook', '0008_auto_20181115_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablebook',
            name='seatno',
        ),
        migrations.RemoveField(
            model_name='tablebook',
            name='tablerate',
        ),
    ]
